robot_cfg:
  name: h1_inspire
  urdf_path: h1_inspire/urdf/h1_inspire.urdf

  dof_num: 51

  left_arm_indices: [13, 14, 15, 16, 17, 18, 19]
  right_arm_indices: [32, 33, 34, 35, 36, 37, 38]
  
  left_arm_init: [0.0, 0.55, -0.3, -0.15, 1.2, 0.3, 0.3]
  right_arm_init: [0.0, -0.55, 0.3, -0.15, -1.2, 0.3, -0.3]

  ee_type: hand
  left_ee: l_ace
  right_ee: r_ace
  
  left_ee_indices: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
  right_ee_indices: [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
  hand_indices: [4, 5, 6, 7, 10, 11, 8, 9, 0, 1, 2, 3]

  # for human input data
  human_hand_indices: [4, 9, 14, 19, 24]
  hand_low_pass_alpha: 0.8
  wrist_low_pass_alpha: 0.5
  
  arm:
    dt:  1e-1
    eps: 1e-4
    damp: 1e-12
    out_lp_alpha: 0.5

  ee:
    left_ee:

      type: vector
      urdf_path: inspire_hand/inspire_hand_left.urdf
      wrist_link_name: "L_hand_base_link"

      # Target refers to the retargeting target, which is the robot hand
      target_joint_names: null
      target_origin_link_names: [ "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_hand_base_link" ]
      target_task_link_names: [ "L_thumb_tip", "L_index_tip", "L_middle_tip", "L_ring_tip", "L_pinky_tip" ]
      scaling_factor: 1.25

      # Source refers to the retargeting input, which usually corresponds to the human hand
      # The joint indices of human hand joint which corresponds to each link in the target_link_names
      target_link_human_indices: [ [ 0, 0, 0, 0, 0 ], [ 4, 9, 14, 19, 24 ] ]

      # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
      low_pass_alpha: 0.5

    right_ee:
      
      type: vector
      urdf_path: inspire_hand/inspire_hand_right.urdf
      wrist_link_name: "R_hand_base_link"

      # Target refers to the retargeting target, which is the robot hand
      target_joint_names: null
      target_origin_link_names: [ "R_hand_base_link", "R_hand_base_link", "R_hand_base_link", "R_hand_base_link", "R_hand_base_link" ]
      target_task_link_names: [ "R_thumb_tip", "R_index_tip", "R_middle_tip", "R_ring_tip", "R_pinky_tip" ]
      scaling_factor: 1.25

      # Source refers to the retargeting input, which usually corresponds to the human hand
      # The joint indices of human hand joint which corresponds to each link in the target_link_names
      target_link_human_indices: [ [ 0, 0, 0, 0, 0 ], [ 4, 9, 14, 19, 24 ] ]

      # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
      low_pass_alpha: 0.5



